language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
script:
- npm run test
- npm run test:e2e
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: develop
  github_token: $TRAVIS_TOKEN